/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UtilPackage;

import BurgerDao.BeveragesDao;
import modal.Package.Beverages;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tyson
 */
public class BuyBeverages extends javax.swing.JFrame {
     BurgersFactory bfact=BurgersFactory.getInstance();
     BeveragesDao bevdao=bfact.registerdrink();
    /**
     * Creates new form BuyBeverages
     */
    public BuyBeverages() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        drinktable = new javax.swing.JTable();
        beverageserial = new javax.swing.JTextField();
        beveragename = new javax.swing.JTextField();
        flavour = new javax.swing.JTextField();
        beverageprice = new javax.swing.JTextField();
        registerdrink = new javax.swing.JButton();
        search = new javax.swing.JButton();
        updatedrink = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Flavour");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        drinktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "BeverageSerial", "BeverageName", "Flavour", "Pricetag"
            }
        ));
        jScrollPane1.setViewportView(drinktable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 180, 540, 90);

        beverageserial.setBackground(new java.awt.Color(240, 240, 240));
        beverageserial.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        beverageserial.setOpaque(false);
        jPanel1.add(beverageserial);
        beverageserial.setBounds(760, 20, 150, 50);

        beveragename.setBackground(new java.awt.Color(240, 240, 240));
        beveragename.setOpaque(false);
        beveragename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beveragenameActionPerformed(evt);
            }
        });
        jPanel1.add(beveragename);
        beveragename.setBounds(760, 80, 150, 50);

        flavour.setBackground(new java.awt.Color(240, 240, 240));
        flavour.setOpaque(false);
        flavour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flavourActionPerformed(evt);
            }
        });
        jPanel1.add(flavour);
        flavour.setBounds(760, 150, 150, 50);

        beverageprice.setBackground(new java.awt.Color(240, 240, 240));
        beverageprice.setOpaque(false);
        jPanel1.add(beverageprice);
        beverageprice.setBounds(760, 220, 150, 50);

        registerdrink.setBackground(new java.awt.Color(255, 255, 255));
        registerdrink.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        registerdrink.setForeground(new java.awt.Color(51, 51, 51));
        registerdrink.setText("Register");
        registerdrink.setOpaque(false);
        registerdrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerdrinkActionPerformed(evt);
            }
        });
        jPanel1.add(registerdrink);
        registerdrink.setBounds(580, 300, 90, 50);

        search.setBackground(new java.awt.Color(255, 255, 255));
        search.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        search.setForeground(new java.awt.Color(51, 51, 51));
        search.setText("Search");
        search.setOpaque(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(820, 300, 90, 50);

        updatedrink.setBackground(new java.awt.Color(255, 255, 255));
        updatedrink.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        updatedrink.setForeground(new java.awt.Color(51, 51, 51));
        updatedrink.setText("update");
        updatedrink.setOpaque(false);
        updatedrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatedrinkActionPerformed(evt);
            }
        });
        jPanel1.add(updatedrink);
        updatedrink.setBounds(700, 300, 90, 50);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Serial Number");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(580, 40, 150, 20);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Pricetag");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(580, 230, 130, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Beverage name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(580, 100, 130, 30);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Flavour");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(580, 160, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\tyson\\Pictures\\Burgers\\fruit-juices-fruit-clipart-juice-png-image-and-clipart-for-free-juice-png-free-download-650_415.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 560, 370);

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\tyson\\Downloads\\juice.png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Burger/images/cancel.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 482, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(979, 471));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void beveragenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beveragenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beveragenameActionPerformed

    private void flavourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flavourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flavourActionPerformed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
           TheBurgerHouse form= new TheBurgerHouse();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MousePressed

    private void registerdrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerdrinkActionPerformed
       Beverages bev=new Beverages();
       
       bev.setSerialnumber(Integer.valueOf(beverageserial.getText()));
       bev.setBeveragename(beveragename.getText());
       bev.setFlavourtype(flavour.getText());
       bev.setPricetag(beverageprice.getText());
        Showdrinks(bev);
       bevdao.create(bev);
       JOptionPane.showMessageDialog(null, "Beverage Created Successfully!");
    }//GEN-LAST:event_registerdrinkActionPerformed

    private void updatedrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatedrinkActionPerformed
        Beverages bev=new Beverages();
       
       bev.setSerialnumber(Integer.valueOf(beverageserial.getText()));
       bev.setBeveragename(beveragename.getText());
       bev.setFlavourtype(flavour.getText());
       bev.setPricetag(beverageprice.getText());
       
       bevdao.Update(bev);
        JOptionPane.showMessageDialog(null, "Beverage Updated Successfully!");
    }//GEN-LAST:event_updatedrinkActionPerformed
    private void Showdrinks(Beverages bev){
        
        DefaultTableModel drink = (DefaultTableModel) drinktable.getModel();
        
        while(drink.getRowCount()>0){
            drink.removeRow(0);
        }
            
            Object[] obj={bev.getSerialnumber(),bev.getBeveragename(),bev.getFlavourtype(),bev.getPricetag()};
            drink.addRow(obj);
        
    }
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        try{
            Beverages b=bevdao.drinksavailable(Integer.valueOf(beverageserial.getText()));
            System.out.println(b);
            Showdrinks(b);
        
        }catch(Exception e){
            System.err.println(e);
        }
        JOptionPane.showMessageDialog(null, "Beverage Found!");
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyBeverages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyBeverages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyBeverages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyBeverages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyBeverages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField beveragename;
    private javax.swing.JTextField beverageprice;
    private javax.swing.JTextField beverageserial;
    private javax.swing.JTable drinktable;
    private javax.swing.JTextField flavour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton registerdrink;
    private javax.swing.JButton search;
    private javax.swing.JButton updatedrink;
    // End of variables declaration//GEN-END:variables
}
